name: Deploy to WordPress.org
on:
  push:
    tags:
      - "*" # Trigger on new tag push
  release:
    types:
      - published  # Triggers on new release
      - edited     # Triggers when a release (including tag) is edited
  workflow_dispatch: # Allows manual trigger
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          fetch-depth: 0 # Ensure all tags are fetched

      - name: Get Tag Name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Debug Tag Name
        run: "echo 'Deploying tag: $TAG_NAME'"

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: 23.7.0

      - name: Install npm dependencies
        run: npm install -g vite

      - name: Make build script executable
        run: chmod +x build-ubuntu.sh

      - name: Run Build Script
        run: ./build-ubuntu.sh

      - name: Clean Up Vendor Folder (Keep Only Composer)
        run: |
          find build/commercebird/vendor ! -path "build/commercebird/vendor" \
          ! -path "build/commercebird/vendor/composer*" \
          ! -name "autoload.php" -exec rm -rf {} +

      - name: Deploy to WordPress.org
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        with:
          path: build/commercebird # Deploy only this directory
          skip_existing: true # Optional, avoids re-deploying existing tags
          generate-zip: true # Optional, generates a zip file for the plugin

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
            files: ${{github.workspace}}/${{ github.event.repository.name }}.zip
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
